// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBldSH_dauZU8DH_jNWKX6UIliLMlggPpU',
    appId: '1:934321345531:web:dc6dc57ae8c11a6034f15e',
    messagingSenderId: '934321345531',
    projectId: 'bonjin-push',
    authDomain: 'bonjin-push.firebaseapp.com',
    storageBucket: 'bonjin-push.appspot.com',
    measurementId: 'G-HQYL5C87MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOmu0dV19wa1bmydewOJNsCRPFL6fkBA',
    appId: '1:934321345531:android:b02fcbeefbb2369134f15e',
    messagingSenderId: '934321345531',
    projectId: 'bonjin-push',
    storageBucket: 'bonjin-push.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5yfNpMDgzBzPDBeakbl4taHetXsBPaIk',
    appId: '1:934321345531:ios:7ceaecdaa5c3e99534f15e',
    messagingSenderId: '934321345531',
    projectId: 'bonjin-push',
    storageBucket: 'bonjin-push.appspot.com',
    iosClientId: '934321345531-bc9raahqrtcksjt517d1mpjcv6n6b57e.apps.googleusercontent.com',
    iosBundleId: 'kr.co.bonjin.push.cloudMessage',
  );
}
