// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6I2gwOR8tdlW3YJxTGjcAw5Hpwno8yQc',
    appId: '1:914159621350:web:d14df55196d613297bd727',
    messagingSenderId: '914159621350',
    projectId: 'flutter-chatting-f93a1',
    authDomain: 'flutter-chatting-f93a1.firebaseapp.com',
    storageBucket: 'flutter-chatting-f93a1.appspot.com',
    measurementId: 'G-6VBWQ7HC9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fNyxXXjx92sm9VnSIJTgdgHg1FaH8sg',
    appId: '1:914159621350:android:a7a30d5892695ba67bd727',
    messagingSenderId: '914159621350',
    projectId: 'flutter-chatting-f93a1',
    storageBucket: 'flutter-chatting-f93a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoEBUYEQp4DigYSLFpLMCzs0uijDWd1zw',
    appId: '1:914159621350:ios:2d5947b74f52c41c7bd727',
    messagingSenderId: '914159621350',
    projectId: 'flutter-chatting-f93a1',
    storageBucket: 'flutter-chatting-f93a1.appspot.com',
    iosClientId: '914159621350-dp22ad6dpdddaff0k1bcr90rs25oafrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoEBUYEQp4DigYSLFpLMCzs0uijDWd1zw',
    appId: '1:914159621350:ios:2d5947b74f52c41c7bd727',
    messagingSenderId: '914159621350',
    projectId: 'flutter-chatting-f93a1',
    storageBucket: 'flutter-chatting-f93a1.appspot.com',
    iosClientId: '914159621350-dp22ad6dpdddaff0k1bcr90rs25oafrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );
}
